parameters:
  - name: ServiceConnection # This is needed as a parameter. Cannot reference from variable group
    type: string
  - name: Location
    type: string
  - name: AppName
    type: string

stages:
  - stage: FunctionAppRelease
    variables:
      - name: webAppName
        value: ${{ parameters.AppName}}
    displayName: Release function app
    jobs:
      - job: DeployFunctionApp
        steps:
          - script: tree
          - task: AzureFunctionApp@2
            displayName: "Publish Function App to Azure"
            inputs:
              azureSubscription: ${{ parameters.ServiceConnection }}
              appType: "functionApp"
              appName: $(webAppName)
              package: "$(Pipeline.Workspace)/WebApp/*.zip"
